[workspace]
name = "spacer"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = ">=3.12"
build123d = ">=0.9"
just = "*"
pytest = "*"

[tasks]
spacer = "just spacer"
strip = "just strip"
render = "just render"
preview = "just preview"
test = "just test"
clean = "just clean"
